export const ALUMNI = [
  {
    id: "a1",
    name: "Priya Sharma",
    role: "alumni",
    batch: "2022",
    company: "TCS",
    designation: "Software Engineer",
    domain: "Web Development",
    location: "Hyderabad",
    experience: "2 years",
    skills: ["React", "Node.js", "MongoDB"],
    bio: "Placed from NCPL in 2022. Happy to mentor trainees in full stack development.",
    email: "priya@example.com",
    available: true,
    avatar: "PS",
    avatarColor: "#1A3C6E",
    connections: 34,
  },
  {
    id: "a2",
    name: "Ravi Kumar",
    role: "alumni",
    batch: "2021",
    company: "Infosys",
    designation: "Java Developer",
    domain: "Backend Development",
    location: "Bangalore",
    experience: "3 years",
    skills: ["Java", "Spring Boot", "MySQL"],
    bio: "NCPL trained me from scratch. Now working at Infosys. Can guide anyone in Java.",
    email: "ravi@example.com",
    available: true,
    avatar: "RK",
    avatarColor: "#7C3AED",
    connections: 52,
  },
  {
    id: "a3",
    name: "Ananya Reddy",
    role: "alumni",
    batch: "2023",
    company: "Wipro",
    designation: "Data Analyst",
    domain: "Data Science",
    location: "Pune",
    experience: "1 year",
    skills: ["Python", "SQL", "Power BI"],
    bio: "Got placed at Wipro after NCPL training. Looking forward to helping current trainees.",
    email: "ananya@example.com",
    available: false,
    avatar: "AR",
    avatarColor: "#059669",
    connections: 28,
  },
  {
    id: "a4",
    name: "Mohammed Farhan",
    role: "alumni",
    batch: "2022",
    company: "Capgemini",
    designation: "QA Engineer",
    domain: "Testing & QA",
    location: "Chennai",
    experience: "2 years",
    skills: ["Selenium", "Jira", "Manual Testing"],
    bio: "QA Engineer at Capgemini. Can help with testing strategies and interview prep.",
    email: "farhan@example.com",
    available: true,
    avatar: "MF",
    avatarColor: "#DC2626",
    connections: 41,
  },
  {
    id: "a5",
    name: "Sneha Patel",
    role: "alumni",
    batch: "2021",
    company: "HCL Technologies",
    designation: "DevOps Engineer",
    domain: "DevOps & Cloud",
    location: "Mumbai",
    experience: "3 years",
    skills: ["AWS", "Docker", "Jenkins"],
    bio: "DevOps at HCL. NCPL gave me the foundation. Happy to mentor anyone interested in cloud.",
    email: "sneha@example.com",
    available: true,
    avatar: "SP",
    avatarColor: "#F4A823",
    connections: 67,
  },
  {
    id: "a6",
    name: "Kiran Babu",
    role: "alumni",
    batch: "2023",
    company: "Tech Mahindra",
    designation: "Android Developer",
    domain: "Mobile Development",
    location: "Hyderabad",
    experience: "1 year",
    skills: ["Kotlin", "Android", "Firebase"],
    bio: "Android dev at Tech Mahindra. Placed from NCPL batch 2023. Ready to guide!",
    email: "kiran@example.com",
    available: true,
    avatar: "KB",
    avatarColor: "#0891B2",
    connections: 19,
  },
];

export const DOMAINS = [
  "All",
  "Web Development",
  "Backend Development",
  "Data Science",
  "Mobile Development",
  "DevOps & Cloud",
  "Testing & QA",
];

export const BATCHES = ["All", "2021", "2022", "2023", "2024"];

export const SUCCESS_STORIES = [
  {
    id: "s1",
    name: "Priya Sharma",
    avatar: "PS",
    avatarColor: "#1A3C6E",
    company: "TCS",
    story: "I had zero coding knowledge before NCPL. After 6 months of training, I cracked my TCS interview. NCPL changed my life!",
    batch: "2022",
    likes: 124,
  },
  {
    id: "s2",
    name: "Ravi Kumar",
    avatar: "RK",
    avatarColor: "#7C3AED",
    company: "Infosys",
    story: "The mentors at NCPL pushed me to go beyond my limits. Got placed in Infosys with a great package. Forever grateful!",
    batch: "2021",
    likes: 98,
  },
  {
    id: "s3",
    name: "Sneha Patel",
    avatar: "SP",
    avatarColor: "#F4A823",
    company: "HCL Technologies",
    story: "From a non-IT background to a DevOps Engineer at HCL — NCPL made this possible. The hands-on training is unmatched.",
    batch: "2021",
    likes: 211,
  },
];